### ISSUE TITLE
Bug/Feature Tracker

### ISSUE THREAD

**Issue by carloskiki** [carloskiki/leptos-icons#4]
### Known Issues
- [x] Twotone icons can't be styled properly
    - A solution for this is to track the `fill` property for every xml tag inside the `svg`. If the overall svg contains two distinct `fill` colors, the darker one would be overwritten to `currentColor`. The lighter color (or the only color if only one `fill` color is set) is the one which corresponds to the secondary tone, and could be set with a css variable or kept track of in the library code. This would permit users to manage the color of twotone icons properly.
- [ ] Explorer site not working on small screens
    - This issue is a simple task, it only requires making a dynamic header with tailwind.
- [x] Code bloat due to generics in component
    - This is theoretically a simple fix, but would require heavier syntax for users. A macro could be made to alleviate this 
       problem.

### Unanswered Questions:
- What should be done about categories (sizes, types, ...)?

**Comment by lpotthast** [comment]
Can you explain how you would like licenses to be handled? Should they be scraped automatically from the downloaded icon packages? We should probably add a note to the readme, saying something like:

"Licenses of the icons provided through this libraries were extracted with best intend, but must only be taken as a hint. Please check the individual icon repositories for up-to-date license information."

**Comment by carloskiki** [comment]
After looking a bit at other libraries, They either simply state each license in the readme, or they provide a `data-attribute` like `data-license="MIT"` to every svg. After consideration I think the way we do it currently is fine, I will quickly add the note which is a good idea.
